CREATE TABLE pets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_type VARCHAR(20) NOT NULL,
  tracker_type VARCHAR(20) NOT NULL,
  owner_id INTEGER NOT NULL,
  in_zone BOOLEAN NOT NULL,
  lost_tracker BOOLEAN,
  created_at   TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_pets_in_zone ON pets(in_zone);
CREATE INDEX idx_pets_group ON pets(pet_type, tracker_type);

-- Give only necessary permissions to the application user
GRANT SELECT, INSERT, UPDATE, DELETE ON pets TO pet_tracking_user;
